base: 'https://femanager.ddev.site/'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: ''
    hreflang: en-US
    direction: ltr
    flag: en-us-gb
    languageId: '0'
rootPageId: 1
routes: {  }
websiteTitle: ''
