version: '3.6'
services:
  web:
    environment:
      - TYPO3_CONTEXT=Development/DDEV
      # Variables for first installation
      - TYPO3_INSTALL_DB_DRIVER=mysql
      - TYPO3_INSTALL_DB_USER=db
      - TYPO3_INSTALL_DB_PASSWORD=db
      - TYPO3_INSTALL_DB_HOST=db
      - TYPO3_INSTALL_DB_PORT=3306
      - TYPO3_INSTALL_DB_USE_EXISTING=1
      - TYPO3_INSTALL_DB_DBNAME=db
      - TYPO3_INSTALL_SITE_SETUP_TYPE=no
      - TYPO3_INSTALL_WEB_SERVER_CONFIG=none
